spice_mix = set()
print(f"Initial spice mix id: {id(spice_mix)}")
print(f"Initial spice mix id {spice_mix}")
spice_mix.add("cardamon")
spice_mix.add("Ginger")
spice.mix.add("cumin")
print(f"After spice mix id: {id(spice_mix)}")
print(f"After spice mix: {spice_mix}")
